/**
 * Copyright 2011 Green Energy Corp.
 *
 * Licensed to Green Energy Corp (www.greenenergycorp.com) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  Green Energy Corp licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.totalgrid.reef.api.request

import org.totalgrid.reef.api.ReefServiceException
import org.totalgrid.reef.proto.Events.{ EventSelect, Event }
import org.totalgrid.reef.api.javaclient.ISubscriptionResult

/**
 * This service is used to get and produce Events on the reef system. Events are generated by the system in response
 * to unusual or interesting occurances, usually they are interesting to an operator but do not require immediate action.
 * When an event is published the system may "upgrade" an Event to also generate an alarm.
 */
trait EventService {
  /**
   * get a single event
   * @param uid event
   */
  @throws(classOf[ReefServiceException])
  def getEvent(uid: String): Event

  /**
   *  get the most recent events
   * @param limit the number of incoming events
   */
  @throws(classOf[ReefServiceException])
  def getRecentEvents(limit: Int): java.util.List[Event]

  /**
   * get the most recent events and setup a subscription to all future events
   * @param limit the number of incoming events
   * @param sub a subscription object that consumes the new Events coming in
   */
  @throws(classOf[ReefServiceException])
  def subscribeToRecentEvents(limit: Int): ISubscriptionResult[java.util.List[Event], Event]

  /**
   * get the most recent events
   * @param types event type names
   * @param limit the number of incoming events
   */
  @throws(classOf[ReefServiceException])
  def getRecentEvents(types: java.util.List[String], limit: Int): java.util.List[Event]

  /**
   * @param selector a selector that allows us to express more specific queries
   * @return all matching events
   */
  @throws(classOf[ReefServiceException])
  def getEvents(selector: EventSelect): java.util.List[Event]

  /**
   * Allows querying and subscribing to specific event types
   * WARNING: not all event selectors are valid for subscriptions
   *
   * @param selector a selector that allows us to express more specific queries
   * @param sub a subscription object that consumes the new Events coming in
   * @return all matching events
   */
  @throws(classOf[ReefServiceException])
  def subscribeToEvents(selector: EventSelect): ISubscriptionResult[java.util.List[Event], Event]

  /**
   * publish a new Event to the system
   */
  @throws(classOf[ReefServiceException])
  def publishEvent(event: Event): Event

}