/**
 * Copyright 2011 Green Energy Corp.
 *
 * Licensed to Green Energy Corp (www.greenenergycorp.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Green Energy
 * Corp licenses this file to you under the GNU Affero General Public License
 * Version 3.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.gnu.org/licenses/agpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.totalgrid.reef.httpbridge.servlets.helpers

import org.totalgrid.reef.client.Subscription
import com.google.protobuf.Message

/**
 * when a subscription is generated by the client we hand it to a handler that is responsible
 * for determining and implemening a transport to carry the subscription data
 */
trait SubscriptionHandler {
  /**
   * add a subcription to be piped to the client
   * @return the token to give to the client
   */
  def addSubscription[A <: Message](subscription: Subscription[A]): String
}

