/**
 * Copyright 2011 Green Energy Corp.
 * 
 * Licensed to Green Energy Corp (www.greenenergycorp.com) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. Green Energy
 * Corp licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
/**
 * <p>
 * Exceptions used and generated by Reef.
 * </p>
 * 
 * <p>
 * Wherever possible exceptions generated inside of the reef client library will subclass from ReefServiceException. During normal operation or
 * "expected failures" all operations should return a subclass of ReefServiceException. Notable exceptions to that rule are the configuration objects
 * which will throw the standard IOException and IllegalArgumentExceptions.
 * </p>
 */
package org.totalgrid.reef.client.exception;